#pragma once
#ifndef ENUM_H_
#define ENUM_H_

namespace OBJ		// 중요도 순으로 뒤로 미루기
{
	enum ID { PLAYER, HAMMER, MONSTER, BULLET, ITEM, FOOD, DATA, OBSTACLE, UI, OBJ_END };
}

namespace DIR
{
	enum DIR { LEFT, RIGHT, UP, DOWN, DIR_END };
}

namespace STATE
{
	enum ID  { IDLE, WALK, ATTACK, JUMP, HIT, DEAD, STATE_END };
}

namespace GAME
{
	enum ID { MENU, STAGEONE, STAGETWO, STAGETHREE, ID_END };
	enum RESULT { NONE, CLEAR, FAIL, RESULT_END };
}

namespace MONSTER
{
	enum ID {  MONSTER, SNAKE, BEE, BAT, DINO, HUMAN, DOG, SPIDER, BIRD, OLD_BIRD, MONSTER_END };
}

namespace BULLET
{
	enum ID { BULLET, HAMMER, BULLET_END };
}

namespace ITEM
{
	enum ID { ITEM, FOOD, GRAPE, CANDY, CAKE, BEER, CANDLE, CANDLE2, HEART, GOLD, CHOCO, CHERRY, EGG, DOUGHNUT,
		DEATH, SCORE750, SCORE20000, BANANA, PAPRIKA, LIFEUP, EXE, GAMEOVER, LEAMON, CANDY2, ICECREAM,
		ICECREAM2, PUDDING, MEAT, ITEM_END };
}

namespace OBSTACLE
{
	enum ID { SAVE, FINAL, OBSTACLE_END};
}
namespace BLOCK
{
	enum ID { DEFAULT, BLOCK2, BLOCK3, ITEM, BLOCK_END };
}

namespace DATA
{
	enum ID { SCORE, LIFES, ENERGY, DATA_END };
}
enum SCENEID { SCENE_LOGO, SCENE_STAGE1, SCENE_STAGE2, SCENE_STAGE3, SCENE_GAME_OVER, SCENE_CLEAR, SCENE_END };
#endif // !ENUM_H_
